apiVersion: v1
kind: Namespace
metadata:
  name: goweb

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gowebtest
  name: gowebtest
  namespace: goweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gowebtest
  template:
    metadata:
      labels:
        app: gowebtest
    spec:
      containers:
      - image: godemo01:3dd1f4b
        name: godemo01
        ports:
        - containerPort: 8888

---
apiVersion: v1
kind: Service
metadata:
  name: gowebtest
  namespace: goweb
spec:
  type: NodePort
  selector:
    app: gowebtest
  ports:
  - name: http
    port: 8888
    targetPort: 8888
    nodePort: 30088