apiVersion: v1
kind: Service
metadata:
  name: gowebtest
  namespace: goweb
spec:
  type: NodePort
  selector:
    app: gowebtest
  ports:
  - name: http
    port: 8888
    targetPort: 8888
    nodePort: 30088